version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8082:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.shatynska.entrypoints=https"
      - "traefik.http.routers.shatynska.rule=Host(`shatynska.in.ua`)"
      - "traefik.http.routers.shatynska.tls=true"
      - "traefik.http.routers.shatynska.tls.certresolver=letsEncrypt"
    networks:
      - traefik-public
      - default
    depends_on:
      - app
    container_name: shatynska_nginx

  app:
    image: getaniftywebsite/php:latest
    volumes:
      - ./:/var/www
      - ./_docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    container_name: shatynska_app
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 8182:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: shatynska_db
    labels:
      - traefik.enable=false
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shatynska_pma
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root 
    restart: always
    ports:
      - 8282:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.shatynskapma.entrypoints=https"
      - "traefik.http.routers.shatynskapma.rule=Host(`pma.shatynska.in.ua`)"
      - "traefik.http.routers.shatynskapma.tls=true"
      - "traefik.http.routers.shatynskapma.tls.certresolver=letsEncrypt"
    depends_on:
      - db
    networks:
      - traefik-public
      - default


networks:
  traefik-public:
    external: true
  default: